### ISSUE TITLE
Justine has three key pain points:

### ISSUE THREAD

**Issue by Yuan05140** [ranyou030/Google-Home#2]
“I can’t find any data on how much energy my smart home products consume!”
“I want to see if our family used more energy this week compared to last week.”
“How do I manage my smart home appliances to reduce my consumption?”

**Comment by verkasum** [comment]
Easy-to-digest reporting screen integrated into the Google Home mobile app
Detailed usage reports filtered by different views and smart home products
Tips on how to optimize smart home products to reduce consumption
